/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "gpio.h"
#include "rcc.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




int main(void)
{

	pin_t pin_tx ;
	pin_t pin_rx ;


	rcc_sys_init_pllr_32MHz_all();
	rcc_ahb1_clk_enable(RCC_GPIOA);
	rcc_apb1_clk_enable(RCC_USART2);

	pin_tx = pin_init(GPIOA,gpio_pin2 ,pin_mode_alternate_fun,pin_push_pull , gpio_null);
	pin_rx = pin_init(GPIOA,gpio_pin3 ,pin_mode_alternate_fun,pin_open_drain , gpio_null);

	pin_af(&pin_rx, AF7);
	pin_af(&pin_tx, AF7);


	 usart_init(USART2, usart_parity_disable, usart_stop_1, 9600, 32000000, usart_mode_no_int);

	/* Loop forever */
	while (1)
	{
		usart_write(USART2, 'M');


	}

}

