/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "cpu.h"
#include "gpio.h"
#include "rcc.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	rcc_sys_init_pllr_32MHz_all();
	rcc_ahb1_clk_enable(RCC_GPIOA);
	sys_delay_init(32000000);
	pin_t led = pin_init(GPIOA, gpio_pin5, pin_mode_output, pin_push_pull, no_pull);



	/* Loop forever */
	while (1)
	{
		pin_level(&led,pin_high);
		delay_ms(1000);
		pin_level(&led,pin_low);
		delay_ms(1000);

	}
}
